version: 2
updates:
  # Automated dependency updates for backend
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"

  # Automated dependency updates for frontend
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
