version: '3.8'

# Development configuration for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # MongoDB - Development configuration
  mongodb:
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: holistic-store

  # Backend API Service - Development mode
  backend:
    build:
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DEBUG: boutique:*
    command: npm run dev

  # Frontend Service - Development mode
  frontend:
    build:
      context: ./client
      target: development
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      # Don't set VITE_API_URL so it uses the proxy in vite.config.js
    ports:
      - "3001:3001"
    command: npm run dev -- --host

  # Nginx - Development configuration
  nginx:
    volumes:
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/html:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx